services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5438:5432'
    environment:
      - POSTGRES_USER=mynthon
      - POSTGRES_PASSWORD=cbbbe50f-e3fc-4ab1-8511-b77f65c27a09
      - POSTGRES_DB=task_manager_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_delayed_message_exchange-3.12.0.ez:/plugins/rabbitmq_delayed_message_exchange.ez
    restart: unless-stopped
    command:
      - bash
      - -c
      - |
        rabbitmq-plugins enable rabbitmq_delayed_message_exchange --offline
        rabbitmq-server

volumes:
  pgdata:
  rabbitmq_data:
