server:
  port: 8090
spring:
  application:
    name: task.manager
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: 'create-drop'
  liquibase:
    enabled: false
    drop-first: false
  datasource:
    url: jdbc:postgresql://localhost:5438/task_manager_db?currentSchema=task_schema
    username: mynthon
    password: cbbbe50f-e3fc-4ab1-8511-b77f65c27a09
    hikari:
      schema: task_manager_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS task_manager_schema
      connection-timeout: 10000
  cloud:
    openfeign:
      client:
        config:
          auth:
            url: 'http://localhost:8090'
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: BASIC
logging:
  level:
    social:
      network:
        account:
          openfeign:
            AccountFeignClient: debug
  pattern:
    console: '%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr([%logger{0}]){cyan} %clr(:){faint} %m%n'
telegram:
  bot:
    token: 8013721798:AAHRcplBYRByZmjAB4C1ZGFnBsheShAcviQ
    username: Task Manager Bot
