server:
  port: 8090
spring:
  application:
    name: task.manager
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: 'none'
  liquibase:
    enabled: true
    drop-first: false
  datasource:
    url: jdbc:postgresql://localhost:5438/task_manager_db?currentSchema=task_schema
    username: mynthon
    password: cbbbe50f-e3fc-4ab1-8511-b77f65c27a09
    hikari:
      schema: task_manager_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS task_manager_schema
      connection-timeout: 10000
  cloud:
    openfeign:
      client:
        config:
          task:
            url: 'http://localhost:8090/api/v1/tasks'
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: BASIC
          user:
            url: 'http://localhost:8090/api/v1/users'
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: BASIC
logging:
  level:
    com:
      mynthon:
        task:
          manager:
            common:
              feign:
                TaskFeignClient: debug
  pattern:
    console: '%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr([%logger{0}]){cyan} %clr(:){faint} %m%n'
telegram:
  bot:
    token: 8013721798:AAHRcplBYRByZmjAB4C1ZGFnBsheShAcviQ
    username: Task Manager Bot
